import { Colors } from "../../constants/colors";

export const styles = {
  header: {
    backgroundColor: Colors.accent,
    width: "100%",
    height: 100,
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    zIndex: 1,
  },
  headerText: {
    color: Colors.white,
    fontSize: 22,
    fontFamily: "TTNorms-Bold",
    position: "relative",
    left: 15,
    top: 10,
  },
  headerImg: {
    tintColor: Colors.white,
    position: "relative",
    left: 25,
    top: 13,
    width: 25,
    height: 38,
  },
  content: {
    height: "100%",
    flexDirection: "column",
    backgroundColor: Colors.appColor,
  },
  contentView: {
    flexDirection: "column",
    justifyContent: "flex-start",
    marginLeft: 40,
    position: "relative",
    top: 15,
  },
  contentSlides: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    height: 55,
    borderBottomWidth: 0.6,
    borderBottomColor: Colors.black,
  },
  contentImg: {
    tintColor: Colors.white,
    width: 20,
    height: 25,
    position: "relative",
    left: 10,
    top: -2,
  },
  contentText: {
    fontSize: 19,
    fontFamily: "TTNorms-Regular",
    position: "relative",
    left: 10,
    color: Colors.white,
    marginLeft: 10,
  },
  switchS: {
    flexDirection: "row",
    alignItems: "center",
    position: "relative",
    left: 300,
    top: -85,
    width: 100,
    height: 100,
  },
  goBack: {
    width: 30,
    height: 25,
    tintColor: "#fff",
  },
  BackView: {
    width: 45,
    height: 45,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
    top: 12,
    left: 8,
    backgroundColor: "transparent",
  },
};
