import { Colors } from "../../constants/colors";
export const styles = {
  header: {
    zIndex: 1,
    marginTop: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    backgroundColor: Colors.boissons,
    width: "100%",
    height: 155,
  },
  searchInputContainer: {
    backgroundColor: Colors.boissons,
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    borderBottomRightRadius: 40,
    borderBottomLeftRadius: 40,
    margin: 5,
    flexDirection: "row",
    alignItems: "center",
    width: "80%",
    height: 40,
    position: "relative",
    top: 32,
    right: 15,
  },
  itemText: {
    zIndex: 1,
    backgroundColor: Colors.white,
    borderTopLeftRadius: 8,
    borderBottomRightRadius: 8,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    alignSelf: "flex-start",
  },
  Container: {
    flex: 1,
    backgroundColor: Colors.dash,
    //flexDirection: "row",
   // justifyContent: "center",
    //alignItems: "center",
  },
  image: {
    //flex: 1
    height: 125,
  },
  imageP: {
    height: 70,
    width: 70,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
    borderBottomLeftRadius: 8,
    position: "relative",
    top: -35,
  },
};
