import { Colors } from "../../constants/colors";

export const styles = {
  header: {
    backgroundColor: Colors.accent,
    width: "100%",
    height: 100,
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    zIndex: 1,
  },
  card: {
    flexDirection: "row",
    justifyContent: "flex-start",
    backgroundColor: Colors.white,
    height: 210,
    borderRadius: 5,
    margin: 10,
  },
  CardHeader: {
    backgroundColor: Colors.info,
    height: 50,
    width: "100%",
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
  },
  CardTextHeader: {
    position: "relative",
    top: 12,
    left: 25,
    fontSize: 17,
    fontFamily: "TTNorms-Regular",
    color: Colors.black,
  },
  CardContent: {
    flexDirection: "column",
    width: 330,
    height: 120,
    position: "relative",
    top: 50,
    right: 372,
  },
  CardContentTitle: {
    position: "relative",
    top: 12,
    left: 25,
    fontSize: 14,
    fontFamily: "TTNorms-Bold",
    color: Colors.black,
  },
  CardTextContent: {
    position: "relative",
    top: 15,
    left: 25,
    fontSize: 14,
    fontFamily: "TTNorms-Regular",
    color: Colors.black,
  },
  CardFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    height: 50,
    zIndex: 1,
    position: "absolute",
    top: 150,
    left: 0,
  },
  FooterButton: {
    width: 135,
    height: 30,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: Colors.darkBlue,
    position: "relative",
    top: 12,
    left: 25,
    borderRadius: 35,
  },
  FooterText: {
    fontSize: 14,
    fontFamily: "TTNorms-Regular",
    color: Colors.white,
    position: "relative",
    left: 33,
    top: -2,
    width: 120,
  },
  FooterToggleText: {
    fontSize: 18,
    fontFamily: "TTNorms-Regular",
    color: Colors.black,
    position: "relative",
    top: 12,
  },
  FooterImage: {
    tintColor: Colors.white,
    width: 17,
    height: 17,
    position: "relative",
    right: 105,
  },
  toggleView: {
    flexDirection: "row",
    justifyContent: "center",
    position: "relative",
    top: 5,
    right: 25,
  },
  goBack: {
    width: 25,
    height: 25,
    position: "absolute",
    top: 50,
    left: 10,
    tintColor: "#fff",
  },
  message: {
    width: 80,
    height: 50,
    position: "absolute",
    top: 435,
    left: 290,
  },
  TexMessage: {
    fontSize: 8,
    fontFamily: "TTNorms-bold",
    color: Colors.black,
    width: 65,
    position: "absolute",
    top: 443,
    left: 300,
    zIndex: 1,
  },
};
